version: '3'

services:
  gowgboard:
    build: .
    ports:
      - "5000:5000"
    privileged: true
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /etc/wireguard:/etc/wireguard
